In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

X_train = [
    "This is a positive sentence.",
    "I love natural language processing.",
    "Negative sentiment detected here.",
    "Logistic regression is a simple algorithm.",
    "I'm not sure about this.",
    "Sentiment analysis is fascinating.",
]
y_train = [1, 1, 0, 1, 0, 1]  # 1 for positive, 0 for negative
X_test = [
    "This is a positive statement.",
    "I enjoy natural language processing.",
    "I detect some negative sentiment here."
]
y_test = [1, 1, 0]
#vectorizer = CountVectorizer(max_features=1000, stop_words='english')
vectorizer = CountVectorizer(max_features=1000)
X_train_bow = vectorizer.fit_transform(X_train)
X_test_bow = vectorizer.transform(X_test)
model = LogisticRegression()
model.fit(X_train_bow, y_train)
y_pred = model.predict(X_test_bow)
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("Classification Report:\n", classification_rep)


Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3



In [ ]:
unique_words = vectorizer.get_feature_names_out()
unique_words

array(['about', 'algorithm', 'analysis', 'detected', 'fascinating',
       'here', 'is', 'language', 'logistic', 'love', 'natural',
       'negative', 'not', 'positive', 'processing', 'regression',
       'sentence', 'sentiment', 'simple', 'sure', 'this'], dtype=object)

In [ ]:
print("\nTF-IDF Matrix (Testing Data):\n", X_train_bow.toarray())


TF-IDF Matrix (Testing Data):
 [[0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1]
 [0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0]]


In [ ]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Sample text data
X_train = [
    "This is a positive sentence.",
    "I love natural language processing.",
    "Negative sentiment detected here.",
    "Logistic regression is a simple algorithm.",
    "I'm not sure about this.",
    "Sentiment analysis is fascinating.",
]
y_train = [1, 1, 0, 1, 0, 1]  # 1 for positive, 0 for negative
X_test = [
    "This is a positive statement.",
    "I enjoy natural language processing.",
    "I detect some negative sentiment here."
]
y_test = [1, 1, 0]

tfidf_vectorizer = TfidfVectorizer(max_features=1000, stop_words='english')
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

model = LogisticRegression()
model.fit(X_train_tfidf, y_train)
y_pred = model.predict(X_test_tfidf)
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("Classification Report:\n", classification_rep)


Accuracy: 0.6666666666666666
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.67      1.00      0.80         2

    accuracy                           0.67         3
   macro avg       0.33      0.50      0.40         3
weighted avg       0.44      0.67      0.53         3



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#print("TF-IDF Matrix (Training Data):\n", X_train_tfidf.toarray())
print("\nTF-IDF Matrix (Testing Data):\n", X_test_tfidf.toarray())


TF-IDF Matrix (Testing Data):
 [[0.         0.         0.         0.         0.         0.
  0.         0.         0.         1.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.57735027 0.
  0.         0.57735027 0.         0.         0.57735027 0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.77326237 0.         0.         0.
  0.         0.6340862  0.         0.        ]]


In [ ]:
unique_words = tfidf_vectorizer.get_feature_names_out()
unique_words

array(['algorithm', 'analysis', 'detected', 'fascinating', 'language',
       'logistic', 'love', 'natural', 'negative', 'positive',
       'processing', 'regression', 'sentence', 'sentiment', 'simple',
       'sure'], dtype=object)

**Lab tasks:**

1. Write a function BagOfWords from scratch which return a matrix based on your training data.
2. Write a function BigramBagOfWords from scratch which return a matrix based on your training data.
2. Write a function TfIDF from scratch which which returns a matrix based on your training data.
3. Write a function LogisticRegression from scratch which computes the probability.